# Generated by Django 2.2 on 2019-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('other', 'Other'), ('electronics', 'Electronic goods'), ('books', 'Books'), ('automotive', 'Automotive'), ('fashion', 'Fashion goods'), ('sports', 'Sports and Outdoors'), ('toys', 'Toys and games')], default='other', max_length=40, verbose_name='Category')),
                ('stock', models.IntegerField(default=0, verbose_name='Left in Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
