# Generated by Django 2.2 on 2019-09-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('Electronics', 'Electronic goods'), ('Books', 'Books'), ('Automotive', 'Automotive'), ('Fashion', 'Fashion goods'), ('Sports', 'Sports and Outdoors'), ('Toys', 'Toys and games'), ('Other', 'Other')], default='Electronics', max_length=40, verbose_name='Status')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
